// Generated by CoffeeScript 1.6.3
var defaultOptions, path, through, transform, _;

through = require('through');

_ = require("underscore");

path = require('path');

defaultOptions = {
  extensions: ['tpl', 'html'],
  templateSettings: {}
};

transform = function(options) {
  options = _.defaults(options  || {}, defaultOptions);
  return function(file) {
    var buffer, isTemplate;
    isTemplate = _.some(options.extensions, function(ext) {
      return path.extname(file) === '.' + ext;
    });
    if (!isTemplate) {
      return through();
    }
    buffer = "";
    return through(function(chunk) {
      return buffer += chunk.toString();
    }, function() {
      var compiled, jst;
      compiled = "";
      jst = _.template(buffer.toString(), void 0, options.templateSettings).source;
      compiled += "module.exports = " + jst + ";\n";
      this.queue(compiled);
      return this.queue(null);
    });
  };
};

module.exports = transform();

module.exports.transform = transform;
